// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjn3i7OzS90XKzBRWbOJi59ee64hHOG0M',
    appId: '1:617473071905:web:49ece88870ce6dc00c7c60',
    messagingSenderId: '617473071905',
    projectId: 'logichatinfofirst',
    authDomain: 'logichatinfofirst.firebaseapp.com',
    storageBucket: 'logichatinfofirst.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt7Sj7qG3mbe47AR9GtIlFJaJdwqpAfNU',
    appId: '1:617473071905:android:0bd68fc4c2dd73e90c7c60',
    messagingSenderId: '617473071905',
    projectId: 'logichatinfofirst',
    storageBucket: 'logichatinfofirst.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLzV273TQVGgn2PNCeLgn7srNXXJCDGQc',
    appId: '1:617473071905:ios:f4157d88903c8dc30c7c60',
    messagingSenderId: '617473071905',
    projectId: 'logichatinfofirst',
    storageBucket: 'logichatinfofirst.firebasestorage.app',
    iosBundleId: 'com.example.backofficeLogistica',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLzV273TQVGgn2PNCeLgn7srNXXJCDGQc',
    appId: '1:617473071905:ios:f4157d88903c8dc30c7c60',
    messagingSenderId: '617473071905',
    projectId: 'logichatinfofirst',
    storageBucket: 'logichatinfofirst.firebasestorage.app',
    iosBundleId: 'com.example.backofficeLogistica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjn3i7OzS90XKzBRWbOJi59ee64hHOG0M',
    appId: '1:617473071905:web:bd86f2a5e7cf758c0c7c60',
    messagingSenderId: '617473071905',
    projectId: 'logichatinfofirst',
    authDomain: 'logichatinfofirst.firebaseapp.com',
    storageBucket: 'logichatinfofirst.firebasestorage.app',
  );
}
